<?php 
		$tmpl_list=array( 
 			'OPENTM201490080'=>array(
 				'name'=>'订单支付成功通知','remark'=>'点此了解详情' 
 			),
			'TM00430'=>array(
					'name'=>'退款成功通知','remark'=>''
			),
			'OPENTM200565259'=>array(
					'name'=>'订单发货提醒','remark'=>'点击查看完整的物流信息'
			),
			'OPENTM202314085'=>array(
					'name'=>'订单确认收货通知','remark'=>''
			),
			'OPENTM200738546'=>array(
					'name'=>'电子凭证验证成功通知','remark'=>''
			),
 		);
		return $tmpl_list;
?>